### ISSUE TITLE
Deprecation message keeps popping up in rails console

### ISSUE THREAD

**Issue by emclab** [jmettraux/ruote-sequel#9]
Here is the ruote.rb under initializers in rails 3.2.12 app:

``` ruby
  require 'rubygems'
  require 'json' # gem install json
  require 'ruote'
  require 'ruote-sequel' # gem install ruote-sequel

  sequel = Sequel.connect('sqlite://development') if Rails.env.development?
  sequel = Sequel.connect('sqlite://test') if Rails.env.test?
  sequel = Sequel.connect('sqlite://ruote_in_rail') if Rails.env.production?

  opts = { 'sequel_table_name' => 'ruote_docs' }
  Ruote::Sequel.create_table(sequel, true, 'ruote_docs') unless   ActiveRecord::Base.connection.table_exists? 'ruote_docs'
  RUOTE_STORAGE = Ruote::Sequel::Storage.new(sequel, opts)

  RUOTE = if defined?(Rake)
    #
    # do not start a ruote worker in a rake task
    #
    Ruote::Dashboard.new(RUOTE_STORAGE)
  else
    #
    # start a worker
    #
    Ruote::Dashboard.new(Ruote::Worker.new(RUOTE_STORAGE))
  end
```

Open cmd window and type rails console under the project directory, there are deprecation messages poping up once in a few seconds:

```
 SEQUEL DEPRECATION WARNING: Symbol#asc is deprecated and will be removed in Sequel 4.0.  Please use Sequel.asc instead, or Sequel.extension(:core_exte
nsions) to continue using it.
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sequel-3.48.0/lib/sequel/deprecated.rb:67:in `block (3 levels) in deprecated_module'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/ruote-sequel-2.3.0/lib/ruote/sequel/storage.rb:413:in `prepare_cache'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/ruote-sequel-2.3.0/lib/ruote/sequel/storage.rb:345:in `begin_step'
C:/Ruby193/lib/ruby/gems/1.9.1/bundler/gems/ruote-2048bc6ad7c6/lib/ruote/worker.rb:239:in `begin_step'
C:/Ruby193/lib/ruby/gems/1.9.1/bundler/gems/ruote-2048bc6ad7c6/lib/ruote/worker.rb:247:in `step'
C:/Ruby193/lib/ruby/gems/1.9.1/bundler/gems/ruote-2048bc6ad7c6/lib/ruote/worker.rb:109:in `run'
C:/Ruby193/lib/ruby/gems/1.9.1/bundler/gems/ruote-2048bc6ad7c6/lib/ruote/worker.rb:120:in `block in run_in_thread'
```

The deprecation message disappears and rails console prompt shows up if RUOTE is defined outside of rails app as:

``` ruby
 RUOTE = Ruote::Dashboard.new(RUOTE_STORAGE)
```

The ruote version is the current one on github.

**Comment by jmettraux** [comment]
Hello,

thanks for the issue.

It's already fixed in https://github.com/jmettraux/ruote-sequel/commit/739e857557ff721f3875599475e6ad315ea16114

You can simply use the ruote-sequel found in github master or I could release a 2.3.0.2 gem

**Comment by jmettraux** [comment]
2.3.0.2 is out http://rubygems.org/gems/ruote-sequel

many thanks!
